spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gymappnew?useSSL=false&serverTimezone=UTC
    username: root
    password: fcl950801
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8080

jwt:
  secret: "change-me-to-a-secure-secret-change-me-123456"
  expiration-seconds: 604800

